import { ProductInfo } from "./types/ProductInfo";

export const Products: ProductInfo[] = [
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../src/assets/Outfit1.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-tshirt',
    category: 'Shirts',
    image: '../src/assets/2013_1373540454_725.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-shirt2',
    category: 'Shirts',
    image: '../src/assets/suishirt.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-shirt3',
    category: 'Shirts',
    image: '../src/assets/tshirt2.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },

  {
    name: 'Adidas Fit Shirt',
    slug: 'adidas-fit-shirt',
    category: 'Shirts',
    image: '../src/assets/Outfit2.jpg',
    price: 100,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    name: 'Lacoste Free Pants',
    slug: 'lacoste-free-pants',
    category: 'Pants',
    image: '../src/assets/Outfit3.jpg',
    price: 220,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'high quality product',
  },
  {
    name: 'Nike Slim Pant',
    slug: 'nike-slim-pant',
    category: 'Pants',
    image: '../src/assets/Outfit31.jpg',
    price: 78,
    countInStock: 15,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 14,
    description: 'high quality product',
  },
  {
    name: 'Iphone14 Pro Max',
    slug: 'iphone-14-pro',
    category: 'Phone',
    image: '../src/assets/Apple-iPhone-14-Pro-Max_52916.jpg',
    price: 1300,
    countInStock: 6,
    brand: 'Iphone',
    rating: 5,
    numReviews: 50,
    description: 'high quality product',
  },
  {
    name: 'Iphone13 Pro Max',
    slug: 'iphone-pro-max',
    category: 'Phone',
    image: '../src/assets/iPhone-13-Pro-Max.jpg',
    price: 1100,
    countInStock: 5,
    brand: 'Iphone',
    rating: 5,
    numReviews: 40,
    description: 'high quality product',
  },
  {
    name: 'Samsung S22 Ultra',
    slug: 'Samsung-S22-Ultra',
    category: 'Phone',
    image: '../src/assets/samsungS22ultra.jpg',
    price: 1000,
    countInStock: 8,
    brand: 'Samsung',
    rating: 5,
    numReviews: 40,
    description: 'high quality product',
  },
  {
    name: 'Xioami 13',
    slug: 'xioami-13',
    category: 'Phone',
    image: '../src/assets/xiaomi13.1.jpg',
    price: 900,
    countInStock: 9,
    brand: 'Xioami',
    rating: 5,
    numReviews: 40,
    description: 'high quality product',
  },

]